### ISSUE TITLE
Capital 'І' have small line/bump on top of it 

### ISSUE THREAD

**Issue by oleksify** [rsms/inter#576] opened 2023-06-02 07:05 UTC
> Did you get the font from Google Fonts? Then please head over to
> https://github.com/google/fonts/issues
> and file an issue with Google Fonts.
> If not, REMOVE THIS PARAGRAPH BEFORE FILING YOUR ISSUE.

**Describe the bug**
Seems like there's something with capital "I". Feels like there's s small bump on the top, and it has different color - darker. I'm testing last beta (v4 beta 9). The issue is appearing on web using variable font.

**To Reproduce**
1. Use capital `І` with variable woff2 in the browser
2. Set CSS with
   ```css
   font-feature-settings: "case" 0, "cpsp" 0, "dlig" 0, "frac" 0, "dnom" 0, "numr" 0, "salt", "subs" 0, "sups" 0, "tnum", "zero", "ss01", "ss02", "ss03" 0, "ss04" 0, "cv01" 0, "cv02", "cv03", "cv04", "cv05" 0, "cv06" 0, "cv07" 0, "cv08" 0, "cv09" 0, "cv10" 0, "cv11" 0, "liga", "calt", "ccmp", "kern";
   ```
3. See the issue

**Expected behavior**
The top of the letter should be flat

**Screenshots**

![242368970-12452d73-fda8-4196-9e40-78f3d272bea7](https://github.com/rsms/inter/assets/29921/9de093df-9659-4986-b109-6a5966fafccc)

**Environment**
- macOS 13.4
- Firefox/Chrome/any browser really
- Version of font - "Inter Variable v4.0-beta9b"

**Comment by rsms** [comment] 2023-06-03 20:08
This is a floating-point rounding error bug in the software rendering the font (a classic.)
I was unable to reproduce this.
Anyhow, I've merged the shapes of /I.1 which works around rounding errors (since there are no more overlapping paths.)

Note that some glyphs do use overlapping shapes that have perfectly-aligning edges which is likely going to cause issues with buggy software, so you might see this kind of thing again.

Also note that this is specific to the variable font. The static font files are preprocessed to have overlapping shapes removed.

**Closed by rsms** 2023-06-03 20:08 UTC
