### ISSUE TITLE
Fix combining diacritics placement in Cyrillic

### ISSUE THREAD

**Issue by peczony** [rsms/inter#214] opened 2019-10-28 21:01 UTC
I took the picture from another bug, because the bug I’m describing can be found there as well.

![](https://user-images.githubusercontent.com/240091/62436840-c5020f00-b6f5-11e9-821c-75b455f7d216.png)

Diacritics should be placed closer to the visual center of the letter, for example, with the letter о it should look the same as the Latin variant: ó

**Comment by rsms** [comment] 2019-11-28 00:57
I believe some of the glyphs have been addressed in #215 and there’s more work to come for the light weights. Closing this out because it’s a duplicate of #181

**Closed by rsms** 2019-11-28 00:57 UTC

**Comment by peczony** [comment] 2020-06-17 10:39
Sorry, I think you might have misunderstood the issue. I tried the latest release, 3.13, today and nothing has changed in this regard although (at least some of) the changes from #215 and #181 have already been included there.

I was talking specifically about combining accent placement, which is the same in all weights and does not affect just thin.

![](https://i.imgur.com/CiDpqhE.png)

Accents in Cyrillic should be placed in the same place as in Latin (sometimes they are indeed placed a bit farther to the right, but not that far)

**Comment by peczony** [comment] 2020-08-17 12:19
@rsms I’m sorry for bothering you, but please consider reopening the issue. I think you might have missed my point first time, so I made a screenshot that better illustrates the issue.

**Comment by rsms** [comment] 2020-08-18 00:29
@peczony Would you mind adding to the conversation in #181?
