### ISSUE TITLE
White dot in `e` letter

### ISSUE THREAD

**Issue by jonhue** [rsms/inter#55] opened 2018-02-16 05:27 UTC
I am using the Inter UI webfont and loving it so far. However, I have one issue with it: the letter `e` has a small white dot where the arc meets the rest of the letter.

![2018-02-16](https://user-images.githubusercontent.com/13420273/36294641-69da0afa-12e2-11e8-87e0-41fed39ed06e.png)

Is that intended? I have to be honest, I'm not a fan of it...

**Comment by rsms** [comment] 2018-02-18 07:02
Duplicate of #51 and fixed in 2.5-beta

**Closed by rsms** 2018-02-18 07:02 UTC
