### ISSUE TITLE
I (eye) and l (ell) are too similar. add 'serif' for capital I (eye) 

### ISSUE THREAD

**Issue by AwokeKnowing** [rsms/inter#196] opened 2019-08-29 19:29 UTC
This font fails it's objectives by making I and l seem like the same letter. This is a huge problem and needs to be reevaluated.  At least capital I (eye) is a bit taller (?)  but it would be so much more practical to just have capital I have a bit of line at top and bottom, purists not withstanding.

**Comment by lordsutch** [comment] 2019-09-04 01:44
This appears to be a duplicate of issue #182.

**Comment by rsms** [comment] 2019-09-04 01:45
duplicate

**Closed by rsms** 2019-09-04 01:45 UTC
