### ISSUE TITLE
Inter UI bold in @fontface turns to "Failed to decode downloaded font" in console

### ISSUE THREAD

**Issue by IgorKurkov** [rsms/inter#61] opened 2018-07-07 13:17 UTC
Maybe this bug was appear when I tried to add font-weights as '600' '800' in font face, but I really need number weights and connect other fonts with them succesfully instead of Inter UI.
So, **solution is**:  to convert them in https://transfonter.org/ and converted files connects normally. But it is not okay, I waste 4 hours to solve this problem.

**Comment by rsms** [comment] 2018-07-20 18:22
Can you please provide the following:

- explanation of the issue (it seems you're only talking about ideas for fixing your problem, but you're not actually explaining what the issue is)
- exact name and version of web browser
- exact name and version of operating system
- version of Inter UI that you're using (if you don't know, you can attach one of the font files to a reply here and I can find out from the file)

**Comment by rsms** [comment] 2018-07-25 17:31
Ping

**Comment by IgorKurkov** [comment] 2018-07-25 17:40
1. Issue is - I was making @fontfaces, add font-weight per each font - bold - 600, semi-bold - 500, regular - 400 etc. In chrome console (anyway) - "Failed to decode downloaded font". Okay. googled. no solution. Only transform fonts on external converters. Maybe this fonts not work with numeric font-weight I guess

**Comment by IgorKurkov** [comment] 2018-07-25 17:41
2. Chrome latest 
3. Mac os High Sierra/ Win7
4. Latest, downloaded few days ago

**Comment by IgorKurkov** [comment] 2018-07-25 17:47
For instance this is already compiled scss code from dist 
```
@font-face{
  font-family:FontAwesome;
  src: url(fontawesome-webfont.674f50d287a8c48dc19b.eot?v=4.7.0);
  src: url(fontawesome-webfont.674f50d287a8c48dc19b.eot?#iefix&v=4.7.0) format('embedded-opentype'),url(fontawesome-webfont.af7ae505a9eed503f8b8.woff2?v=4.7.0) format('woff2'),url(fontawesome-webfont.fee66e712a8a08eef580.woff?v=4.7.0) format('woff'),url(fontawesome-webfont.b06871f281fee6b241d6.ttf?v=4.7.0) format('truetype'),url(fontawesome-webfont.912ec66d7572ff821749.svg?v=4.7.0#fontawesomeregular) format('svg');
  font-weight:400;
  font-style:normal
}
```

**Comment by rsms** [comment] 2018-08-27 16:02
Lack of details, reproduction steps and activity, I'm closing this issue.
If you have a detailed set of steps to reproduce this, please post here and we can reopen this issue and investigate.

**Closed by rsms** 2018-08-27 16:02 UTC
