### ISSUE TITLE
Broken Greek letters U+03C9 and U+03CE in 3.13

### ISSUE THREAD

**Issue by GadQ** [rsms/inter#295] opened 2020-07-02 08:08 UTC
Those 2 letters are present, but display incorrectly in version 3.13, in 3.12 they were OK.
Affected weights in 3.13:
Semibold
SemiboldItalic
Bold
BoldItalic

### Screenshots
**3.12:**
![3 12](https://user-images.githubusercontent.com/2109463/86321323-0fa74680-bc39-11ea-8a26-23a6db13a940.png)

**3.13:**
![3 13](https://user-images.githubusercontent.com/2109463/86321322-0f0eb000-bc39-11ea-999e-b2cd3046af2d.png)

**Comment by Felix-MFU** [comment] 2020-07-05 10:32
I also saw this. The intermediate weights are faulty although starting points match. Merging shapes within each weight and fixing up overlap of Thin Italic did it for me. Unfortunately I can't push my version.

**Comment by rsms** [comment] 2020-08-17 17:23
Good catch! Thank you.

![asdm81o](https://user-images.githubusercontent.com/47046/90424860-a73ee800-e073-11ea-9151-901d8a76c692.gif)
Oops :-)

**Comment by rsms** [comment] 2020-08-17 17:25
Oh, I just realized this has been fixed (but not yet released). Duplicate of #272

**Closed by rsms** 2020-08-17 17:25 UTC
Labels: bug
