### ISSUE TITLE
Add Uniwidth variants

### ISSUE THREAD

**Issue by naiyerasif** [rsms/inter#351] opened 2021-02-17 09:24 UTC
Since, Inter is widely used on the web, a uniwidth variant of the font will help avoid layout shifts when a state change is indicated by a change in weight.

**Additional context**
Consider a button with text displayed in regular weight. The weight is styled to shift to bold when a user hovers / focuses on the button. Currently, changing the weight changes the dimensions of the button. In case of uniwidth variant, this would not happen.

For more context, please refer to Lisa Staudinger's excellent piece on [Uniwidth typefaces for interface design](https://uxdesign.cc/uniwidth-typefaces-for-interface-design-b6e8078dc0f7). The following GIF from the mentioned article showcases this request (with a comparison between IBM Plex Sans which is not a uniwidth font and Recursive which is).

![Using a uniwidth typeface one can easily animate the weight of interactive text elements without affecting the surrounding layout.](https://user-images.githubusercontent.com/19614213/108182164-bbe95f00-712e-11eb-888e-af5744e809d9.gif)

**Comment by KrasnayaPloshchad** [comment] 2021-03-01 18:17
This could be done by adding `hwid` feature

**Comment by rsms** [comment] 2021-03-28 21:13
Thanks @KrasnayaPloshchad but I think @naiyerasif is asking for a monospace version of inter; where the width of all glyphs. My understanding is that [`fwid`](https://docs.microsoft.com/en-us/typography/opentype/spec/features_fj#tag-fwid) is specifically for CJK fullwidth glyphs and wouldn't be appropriate nor probably solve the problem in this case.

[Recursive](https://www.recursive.design) is an example of a variable font with a custom `MONO` axis which accomplishes what is being asked for.

However, Inter Mono is currently **not planned.** It might never happen. There are simply so many good, freely-available monospace typefaces out there, many that works well with Inter.

Here are a few freely-available fonts you can try @naiyerasif with Inter: JetBrains Mono, Recursive, Roboto Mono, Hack, Inconsolata

**Comment by rsms** [comment] 2021-03-28 21:14
Duplicate of #128

**Comment by naiyerasif** [comment] 2021-03-29 12:58
@rsms I am definitely not asking for monospace version 😺 . Once again I'll quote from Lisa's article linked above:

> A **monospaced font**, also called **non-proportional font**, is a font whose letters and characters each occupy the same amount of horizontal space (e.g. an uppercase *A* is the same width as a lowercase *w*, or a *€*-sign ). Monospaced fonts are traditionally used for typewriters, or nowadays for setting computer code.
>
> **Uniwidth** typefaces, on the other hand, are **proportionally-spaced** typefaces, but every character occupies the same space across different cuts or weights. What this means in practice is that no matter which weight you set your text in, it will never change its length or cause text to reflow.

Uniwidth typefaces solve a very specific problem: text reflow / layout shifts when font-weight is used as a cue to indicate a change on an event (like focus or hover of a cursor). I embedded a gif above that illustrates this.

**Comment by rsms** [comment] 2021-03-31 20:53
Got it! Thanks for the clarification.
It would be too much work to do this manually for a second family I think, but it may be possible to generate automatically from source. I'm thinking something like this:

```
for each glyph
  compute relative LSB & RSB for current bounding box
  let W be max(x)-min(x) of all masters for glyph
  adjust LSB & RSB so that glyph's width is equal to W
```

This may be good enough. Thoughts?

**Comment by naiyerasif** [comment] 2021-04-04 15:25
@rsms Automating this would make sense. I'm definitely not qualified enough to comment on _how_ part. Maybe @KrasnayaPloshchad can remark on that?

**Comment by robzg420** [comment] 2022-09-02 20:01
I think you can simulate the uniwidth behaviour by adjusting the letter spacing. Not a scalable solution, but it might help in some cases. In this example, I added `letter-spacing: 0.02em;` to the smaller weight.

![Screen Recording 2022-09-02 at 22 22 29](https://user-images.githubusercontent.com/100498311/188223273-6392bff3-ef0f-4e98-9604-52911b2c6fc3.gif)

**Comment by naiyerasif** [comment] 2023-09-09 08:03
It has been a while since I raised this request. I've found a new usecase for adding a `GRAD` axis: it allows me to adjust the contrast for a font to support light and dark modes. An example of this in action using Roboto Flex is here: https://youtu.be/8B7xOgp5Aow

**Comment by rsms** [comment] 2024-11-19 02:59
Shipped with version 4.0

**Closed by rsms** 2024-11-19 02:59 UTC
Labels: Add

**Comment by KTibow** [comment] 2024-12-21 02:56
How can I use uniwidth bold or grade? I can't find any reference to uniwidth options or grade in Inter.

**Comment by mrjbq7** [comment] 2025-01-31 19:08
> Shipped with version 4.0

How do I use the uniwidth version? Thanks!

**Comment by krystean** [comment] 2025-04-17 19:42
@rsms Hi, thank you for your work! While this issue is closed, I can't seem to find the option to set uniwidth variants for letters. The only option that works is tabular figure widths. Is there a way to apply tabular widths to letters?

**Comment by kenmcd** [comment] 2025-04-17 23:41
No.
The only "uniwidth" glyphs are for the Tabular Figures (`tnum`) feature.
They are the same width for all weights (multiplexed)
It includes all the figures, plus basic math characters, plus punctuation, and a figurespace. (`2007`). 
The figures, math, figurespace, etc. are all 1338 wide.
The punctuation and spaces are 550 wide.
This is too support presenting tables of figures, etc.
Note: the math and punctuation also have Case Sensitive Forms (`case`) so they look better with uppercase text.
That is why you see the duplicates.

These are the glyphs for Inter v4.1/v4.001 below:

![Image](https://github.com/user-attachments/assets/2ef8e3af-8269-4656-9e77-6b971999a8dd)

Making Inter able to support uniwidth for all glyphs would be a huge undertaking.
It would require a number of new masters, and thousands of new glyphs.
Many, many, many hours of work.
Not likely to happen.

**Comment by krystean** [comment] 2025-04-18 01:42
Thanks!

> Making Inter able to support uniwidth for all glyphs would be a huge undertaking. It would require a number of new masters, and thousands of new glyphs. Many, many, many hours of work. Not likely to happen.

I'm curious what rsms' pseudocode for automatically generating the glyphs would produce. An experimental build would be awesome.
