### ISSUE TITLE
STAT field designAxisCount seems to be wrong

### ISSUE THREAD

**Issue by herrernst** [rsms/inter#311] opened 2020-08-20 15:02 UTC
I tried to open the variable font in this tool: https://lorp.github.io/samsa/src/samsa-gui.html
But it didn't work. Author of the tool says your font file is broken: https://github.com/Lorp/samsa/issues/49

**Comment by rsms** [comment] 2020-08-20 15:53
Duplicate of #308

**Closed by rsms** 2020-08-20 15:53 UTC
