### ISSUE TITLE
Combining character combines with the following character

### ISSUE THREAD

**Issue by dscorbett** [rsms/inter#335] opened 2020-11-29 15:43 UTC
Some base characters combine with a preceding combining enclosing character, but they should only combine with a _following_ combining character.

**Screenshot**
Here is <U+20DD, U+0041>. This glyph should actually correspond to <U+0041, U+20DD>.
![⃝A](https://user-images.githubusercontent.com/1124347/100546380-17423a00-322f-11eb-9171-fa63d37e0317.png)

**Environment**
- OS: macOS 10.14
- Version of font: 3.15

**Comment by rsms** [comment] 2020-12-16 00:21
This is intended behavior ([source](https://github.com/rsms/inter/blob/f1275e09e9f08a6afdfb547de321cb4268ef94a8/src/features/ccmp.fea#L745))

Is there a scenario where this behavior is causing you trouble? Could you share that to help us consider whether to change this or not? The reason it combines in either order is to make it easier for people to use. I've first hand sat down with designers watching them use this and even the most aware people struggled to remember the "correct" order which led me to implement support for any order.

**Comment by dscorbett** [comment] 2020-12-16 01:23
This bug is not causing me trouble personally. The reason not to allow either order is that it violates the standard. It encourages people to create documents that look right with this font but are incompatible with other fonts. In Unicode, combining characters follow base characters; see [figures 2-17 and 2-18 of <i>The Unicode Standard</i>](https://www.unicode.org/versions/Unicode13.0.0/ch02.pdf#page=48).

**Comment by moyogo** [comment] 2021-03-29 05:11
This is an input problem that should not be fixed in the font but in the input method.

A better approach would be to make it obvious to the user that the order is incorrect for example by making it look like:  ◯A.

**Comment by rsms** [comment] 2021-03-29 23:39
@moyogo oh that's a nice idea. I'll try it...

**Closed** 2021-03-30 00:09 UTC
Labels: Needs Info, design, technical

**Comment by rsms** [comment] 2021-03-30 00:10
That worked nicely. I'll include the change in the next release 3.18.
Here's a screenshot of 9b8f3f1b5ae495f0da18c17012d0689edab7f828 in the lab showing codepoints in the wrong order does not compose but instead substitutes the enclosing glyphs with full-width counterparts:
<img width="966" alt="Screen Shot 2021-03-29 at 17 07 47" src="https://user-images.githubusercontent.com/47046/112914766-b5e18900-90b1-11eb-9d5f-07e47c5f7d22.png">

**Comment by rsms** [comment] 2021-04-01 02:12
[Released with v3.18](https://github.com/rsms/inter/releases/tag/v3.18)
