### ISSUE TITLE
Add grade axis or a multiplexed version for animations

### ISSUE THREAD

**Issue by Nick-Mazuk** [rsms/inter#554] opened 2023-04-07 05:10 UTC
In designs, you'll often want to use a heavier font weight to denote emphasis. And often it's great to animate between the unemphasized and emphasized state. While you can do that with Inter's weight axis, that changes the width of text which can cause layout shift (and that's bad UX). However, if Inter had the grade variable axis or had a multiplexed version where different weights were the same width, these animations become possible.

Font animations: https://fonts.google.com/knowledge/using_variable_fonts_on_the_web/interactive_animations_with_variable_fonts

Multiplexing: https://fonts.google.com/knowledge/glossary/multiplexed_duplexed_uniwidth

Grade: https://fonts.google.com/knowledge/glossary/grade_axis

**Comment by rsms** [comment] 2023-04-08 17:44
Duplicate of #351

**Closed** 2023-04-08 17:44 UTC
