### ISSUE TITLE
The Black weight is being used as the default weight of Inter

### ISSUE THREAD

**Issue by aemi-dev** [rsms/inter#498] opened 2022-09-29 22:27 UTC
**Describe the bug**
The Inter default weight is the Black which is kind of problematic if you set Inter as the default font in your browser (assuming a Chromium based here) and reading through a site which use your default font.

**To Reproduce**
1. Set Inter as your default font in a Chromium based browser
2. Go to Wikipedia and read any article
3. Notice the black weight version being used everywhere

**Expected behavior**
The Regular version should be the default one.

**Screenshots**
<img width="1599" alt="Screenshot 2022-09-30 at 00 14 03" src="https://user-images.githubusercontent.com/42325924/193151941-a2d169ef-2cee-4fea-8352-44b111b91601.png">

https://user-images.githubusercontent.com/42325924/193153208-b983a3a7-3a29-47de-b9a5-15d81a8604bc.mp4

**Environment**
- OS: macOS 13.0 Beta (22A5358e)
- Arc Browser 0.70.0 (34916) (Chromium Engine Version 106.0.5249.62), Affinity Designer, Pixelmator Pro
- Inter v4 beta 1

**Comment by rsms** [comment] 2022-09-30 02:19
- What specific font file(s) are you using?
- How do you specify the font in Arc?

**Comment by aemi-dev** [comment] 2022-09-30 09:48
I'm using the Desktop files and Arc being a Chromium browser, it's set the same way other Chromium ones use:

It acts the same way with Desktop files and Hinted Desktop files by the way.

Arc:
<img width="1384" alt="Screenshot 2022-09-30 at 11 40 44" src="https://user-images.githubusercontent.com/42325924/193242374-869065f4-e79f-44a0-92b5-e5fce29d8181.png">

Chromium (Last Version):
<img width="1153" alt="Screenshot 2022-09-30 at 11 46 22" src="https://user-images.githubusercontent.com/42325924/193243709-1ac75005-47a4-499d-8749-2120c9dfbef4.png">

macOS Ventura Font Book Installation Pop-Up:
<img width="612" alt="Screenshot 2022-09-30 at 11 45 47" src="https://user-images.githubusercontent.com/42325924/193243770-4fda43fe-26fb-42b2-b499-bbc698cd693f.png">

**Comment by rsms** [comment] 2022-09-30 16:30
Very strange.

> Chromium (Last Version):

For me, with Chrome 106.0.5249.91 and the fonts in "Desktop" folder from [the latest v4 beta](https://github.com/rsms/inter/discussions/463#discussion-4105311) works correctly:
<img width="1096" alt="Screen Shot 2022-09-30 at 09 28 12" src="https://user-images.githubusercontent.com/47046/193315740-9af4ccc9-6882-4e54-8e94-6085cd218de5.png">


> macOS Ventura Font Book Installation Pop-Up:

For what font file? (you say you are using fonts in the "Desktop" folder, so which one of them did you open to get this screenshot?)

With [the latest v4 beta](https://github.com/rsms/inter/discussions/463#discussion-4105311) it looks fine on macOS 10.15 for me. Can you select the info tab for inter like this in Font Book and share a screenshot?
<img width="1084" alt="Screen Shot 2022-09-30 at 09 27 16" src="https://user-images.githubusercontent.com/47046/193315295-1fab329c-cfbf-44ca-94f5-c2a921b8c527.png">

**Comment by aemi-dev** [comment] 2022-10-01 10:51
Here's a video of the full installation and usage.
https://user-images.githubusercontent.com/42325924/193406024-9c5cf7eb-0772-4d7e-85c1-23050a31b7e3.mov

It appears the last Chromium/Chrome/Canary do not load Wikipedia with an error in the font loading but Arc does so I'll report a bug to them also for the different behaving.

But Affinity/Pixelmator still load Black Inter as the default Inter which is a bit weird.

**Comment by rsms** [comment] 2022-10-03 16:16
Can you please show me **exactly** what font files you have installed? Either through font book as I requested earlier or via Finder. I want to make sure you have the static fonts in the "Desktop" folder installed and not the variable one.

**Comment by aemi-dev** [comment] 2022-10-04 01:32
It seems, the video is too heavy but github provided this link: https://user-images.githubusercontent.com/42325924/193406024-9c5cf7eb-0772-4d7e-85c1-23050a31b7e3.mov
It's not the same as the previous preview, it's an other that shows exactly the process.

**Comment by rsms** [comment] 2022-10-04 01:52
Please, I just need to know EXACTLY what font files you have installed. I appreciate the effort with the videos, but it’s not effective (that last video doesn’t play on my iPhone.)

**Comment by aemi-dev** [comment] 2022-10-04 21:45
[Inter-4.00-3f174fcef6-Desktop.zip](https://github.com/rsms/inter/files/9711050/Inter-4.00-3f174fcef6-Desktop.zip)

I'm doing my best, I said it was "Desktop" files, from the Inter 4 beta 1, from the zip available on the tags page of GitHub, so those files you built.

This is the version the fontbook shows: `Version 4.000;git-3f174fcef` (already said earlier in a comment)

<img width="1370" alt="Screenshot 2022-10-04 at 23 38 36" src="https://user-images.githubusercontent.com/42325924/193935591-4cf77375-41d5-42c9-b102-ade99f730e89.png">

I literally made a `cmd+a` in `/Users/.../Downloads/Inter-4.00-3f174fcef6/Desktop/`, right click, open, `OK` button, `Install` button. What do you want more ? SHA512 hashes ? 😂 

```
0aecea29bdc2688448260346bd404a7fae5cdbaa630582f8f074622cd778d84c  ./Inter-Black.otf
3d3c3a1c396f33b2595297b490aba4791389474ed1c61b4e5ca750f06631450c  ./Inter-BlackItalic.otf
a2d643bb7e569e3906ce85adbfbae6b07814e08f273165ad691964d69dab280c  ./Inter-Bold.otf
32c68dc322bf2236efd145c1232e09b46cb226baeccdec48dc1eb6174789bf0f  ./Inter-BoldItalic.otf
da44ac18c3d29291f541a44aeb71b75678486b3631490ac8faeb93616bdddbb8  ./Inter-DisplayBlack.otf
211339ce1cdd59ad406eb0660fbfc99b2cf3f63d00baf8374147418ed35e6e32  ./Inter-DisplayBlackItalic.otf
2a794edeca3cac203053c2c296c70738e04cf248bb35ac398f21d6e62ff829ff  ./Inter-DisplayBold.otf
2303411138ced1f43ad4a0acf91e0a7d6214e5b8a71630d3ed93a8ce2f769fa7  ./Inter-DisplayBoldItalic.otf
501ac362911083ece610556254ed0358598d772bcf7eb6a78c50777282e4625c  ./Inter-DisplayExtraBold.otf
6c60d264de644e7b19e1518e6a5b87461dd8368583e3aaca676b1bd18ea6a44e  ./Inter-DisplayExtraBoldItalic.otf
2982146dbce0b1c4b4169990592e9d6a035a64dfcb541200aee475ee886617ad  ./Inter-DisplayExtraLight.otf
0e1446ee9983c1c498796cb55c3062bf2a9d53e2bf55f3e85bf9c6baf3af63f3  ./Inter-DisplayExtraLightItalic.otf
468b2dbc8a73527d070e17a740ab12c6fabe2a4f34c7f0693a9b49c7e8bcefd0  ./Inter-DisplayItalic.otf
046fa316d2cbde5dab08e1b284e0785e639df539332815b312fcb7f73f14a385  ./Inter-DisplayLight.otf
47869e412a79e07d6f421f4c235b732fc26e0af8b86e6999390e3fe0f9052b99  ./Inter-DisplayLightItalic.otf
5ee460be7cbf1695426b163ba2bab4010b6185bc7211044f444f9ffa6366747e  ./Inter-DisplayMedium.otf
b574a23778aa3f9b39b235ca301679d6dcf7ed5271342fdebfc8eb53744f3676  ./Inter-DisplayMediumItalic.otf
fed1981dbde1bf6414f7a298c589428476e7f8e15de93558f78fa665f0f30d45  ./Inter-DisplayRegular.otf
1f2a615fb44dac44991c20ea33b7095742d01440893951a6877ff8d8e9f4234b  ./Inter-DisplaySemiBold.otf
3c421778c9442e321c91a2cb11387a5ed8bdd082446a81d0c269d01cbdb46590  ./Inter-DisplaySemiBoldItalic.otf
aaa2bfd00f4a97b3521acbdb6e668e62fb3fbac01ccce30fc91e1d03bf5ed485  ./Inter-DisplayThin.otf
2aa984bda165b63e79b970093da218cb933a4af9925cfdc7f4bf3875d4c2ef80  ./Inter-DisplayThinItalic.otf
9acd326b3a28aec31df8716c6a5813be48fd89cf36fbece9a206798769e1ad39  ./Inter-ExtraBold.otf
0469feb7f921aa76135a3de4a55ae49d78cc5961c5ae733ee44467d07131cc3f  ./Inter-ExtraBoldItalic.otf
5bf9a9868f26e1d546f4b3bb45da9cbf9f0dc7de38f5ece3dd7115cd95bddbef  ./Inter-ExtraLight.otf
7d0282bbaad4101cf3b0a6c5a070868094a6974a7aad228a6a5cd448300920f4  ./Inter-ExtraLightItalic.otf
a7a78e99ccdfd70ff13c726ad509b38308ac1a8eea7bdd01df16e398dc96e461  ./Inter-Italic.otf
93fa6638edaf861d676c00c92c1904c622effec9cbd07e995c58137d77ad05e3  ./Inter-Light.otf
1620510eb64e21d6883cb97d9f2f06daf260cacb659a719d07db2caa8ef5c788  ./Inter-LightItalic.otf
e300aff493f831a6bcc6ce55b1fec16639d55608318634d8f1d79920f25de387  ./Inter-Medium.otf
aeab99ee1b0fa1ffe32ce61f13b5dc9a9d9359a9440482cc3246c0a239a9f433  ./Inter-MediumItalic.otf
ecf7e2a8a9e69467d315c4965566233e05f59d44e194d3813f9cd970c0af19ba  ./Inter-Regular.otf
e3889070ea014b993d95afcf9f07d475509acaa76fa1c8809c44d4a13de024f0  ./Inter-SemiBold.otf
8cd828369db26eecf539a49b18fe07e0f304a3c4687bb2bfb980800cf17e81a1  ./Inter-SemiBoldItalic.otf
b4d5517a442081b9520960a9552df2b944d2548c9b6afd3b9a2c2e0fb85dcaf4  ./Inter-Thin.otf
5ad226c2bede4ad1d65ba9b80695089068b14aae3863fd9f2068525aea7c1b20  ./Inter-ThinItalic.otf
```

Please tell me what evidence you're looking forward to. Anyway, just saw you released b2, I will try it.

**Comment by rsms** [comment] 2022-10-05 01:01
Since I can't reproduce this myself in Chrome or on macOS, I must assume that there's something fishy going on (for example duplicate versions of Inter in your ~/Library/Fonts directory, sourcing the variable font.)

As you seem comfortable with using a terminal/shell, try this:

```
find ~/Library/Fonts -iname '*inter*' &&
find /Library/Fonts -iname '*inter*'
```

And paste the output in a reply here.
Thanks!

**Comment by kenmcd** [comment] 2022-10-05 01:06
There are some issues with the static fonts.
Names and weights are a bit off.
The images below are from the v4 Beta 2 Desktop fonts.
From the zip - Inter-4.00-21e1b48910.(2022-10-04).zip

This is just the Normal fonts:
Note that the Black and Thin fonts are also set to 400.
![Inter 4 Beta 2 Desktop Normal issues](https://user-images.githubusercontent.com/844920/193957337-ab2b5d6d-00f7-4856-88f6-5b62696ef2e9.png)

This is just the display fonts:
Again, Note that the Black and Thin fonts are also set to 400.
And the Bold fonts are in their own style groups.
![Inter 4 Beta 2 Desktop Display issues](https://user-images.githubusercontent.com/844920/193957546-aa04bf66-72d3-40d8-937c-dec607a7405a.png)

Perhaps the Black being set to 400 is confusing the applications.

**Comment by aemi-dev** [comment] 2022-10-05 06:54
```

/Users/gc/Library/Fonts/Inter-Bold.otf
/Users/gc/Library/Fonts/Inter-Regular.otf
/Users/gc/Library/Fonts/Inter-SemiBoldItalic.otf
/Users/gc/Library/Fonts/Inter-Thin.otf
/Users/gc/Library/Fonts/Inter-Light.otf
/Users/gc/Library/Fonts/Inter-V.ttf
/Users/gc/Library/Fonts/Inter-ExtraLightItalic.otf
/Users/gc/Library/Fonts/Inter-Medium.otf
/Users/gc/Library/Fonts/Inter-SemiBold.otf
/Users/gc/Library/Fonts/Inter-BlackItalic.otf
/Users/gc/Library/Fonts/Inter-MediumItalic.otf
/Users/gc/Library/Fonts/Inter-Black.otf
/Users/gc/Library/Fonts/Inter-Italic.otf
/Users/gc/Library/Fonts/Inter-ExtraBold.otf
/Users/gc/Library/Fonts/Inter-ThinItalic.otf
/Users/gc/Library/Fonts/Inter-ExtraLight.otf
/Users/gc/Library/Fonts/Inter-ExtraBoldItalic.otf
/Users/gc/Library/Fonts/Inter-BoldItalic.otf
/Users/gc/Library/Fonts/Inter-LightItalic.otf
```

This is the result when I have the Inter font files installed from `brew install --cask font-inter` (Inter 3.19). But when I try the Inter 4 files, I uninstall these files and install only the Inter 4 files. And of course, there's no remaining files when I uninstall those brew ones.

And this is the output after manual installation of the beta version:

```
/Users/gc/Library/Fonts/Inter-Bold.otf
/Users/gc/Library/Fonts/Inter-DisplayBlackItalic.otf
/Users/gc/Library/Fonts/Inter-DisplayMedium.otf
/Users/gc/Library/Fonts/Inter-DisplayExtraBold.otf
/Users/gc/Library/Fonts/Inter-Regular.otf
/Users/gc/Library/Fonts/Inter-DisplaySemiBold.otf
/Users/gc/Library/Fonts/Inter-DisplayLight.otf
/Users/gc/Library/Fonts/Inter-DisplayExtraBoldItalic.otf
/Users/gc/Library/Fonts/Inter-SemiBoldItalic.otf
/Users/gc/Library/Fonts/Inter-Thin.otf
/Users/gc/Library/Fonts/Inter-Light.otf
/Users/gc/Library/Fonts/Inter-DisplayRegular.otf
/Users/gc/Library/Fonts/Inter-ExtraLightItalic.otf
/Users/gc/Library/Fonts/Inter-DisplayBold.otf
/Users/gc/Library/Fonts/Inter-Medium.otf
/Users/gc/Library/Fonts/Inter-DisplayLightItalic.otf
/Users/gc/Library/Fonts/Inter-DisplayThin.otf
/Users/gc/Library/Fonts/Inter-DisplayThinItalic.otf
/Users/gc/Library/Fonts/Inter-DisplayExtraLight.otf
/Users/gc/Library/Fonts/Inter-DisplayExtraLightItalic.otf
/Users/gc/Library/Fonts/Inter-SemiBold.otf
/Users/gc/Library/Fonts/Inter-BlackItalic.otf
/Users/gc/Library/Fonts/Inter-DisplayBoldItalic.otf
/Users/gc/Library/Fonts/Inter-MediumItalic.otf
/Users/gc/Library/Fonts/Inter-Black.otf
/Users/gc/Library/Fonts/Inter-Italic.otf
/Users/gc/Library/Fonts/Inter-DisplayBlack.otf
/Users/gc/Library/Fonts/Inter-ExtraBold.otf
/Users/gc/Library/Fonts/Inter-ThinItalic.otf
/Users/gc/Library/Fonts/Inter-DisplayItalic.otf
/Users/gc/Library/Fonts/Inter-ExtraLight.otf
/Users/gc/Library/Fonts/Inter-ExtraBoldItalic.otf
/Users/gc/Library/Fonts/Inter-BoldItalic.otf
/Users/gc/Library/Fonts/Inter-DisplayMediumItalic.otf
/Users/gc/Library/Fonts/Inter-DisplaySemiBoldItalic.otf
/Users/gc/Library/Fonts/Inter-LightItalic.otf
```

@kenmcd This is completely what I suspected.

**Comment by rsms** [comment] 2022-10-05 16:41
Filed an issue with fontmake: https://github.com/googlefonts/fontmake/issues/943

**Comment by rsms** [comment] 2022-10-05 17:07
> ![Inter 4 Beta 2 Desktop Normal issues](https://user-images.githubusercontent.com/844920/193957337-ab2b5d6d-00f7-4856-88f6-5b62696ef2e9.png)

@kenmcd I'm curious what tool this is that has such a nice UI for style linking? Style liking is a complete mystery to me.

**Comment by aemi-dev** [comment] 2022-10-05 18:26
@rsms This is TransType https://www.fontlab.com/font-converter/transtype/.
The last time I tried to use it, it was not compatible with M1 Macs, but it seems they updated it.

Going to try it again.

**Comment by kenmcd** [comment] 2022-10-05 19:34
> > ![Inter 4 Beta 2 Desktop Normal issues](https://user-images.githubusercontent.com/844920/193957337-ab2b5d6d-00f7-4856-88f6-5b62696ef2e9.png)
> 
> @kenmcd I'm curious what tool this is that has such a nice UI for style linking? Style liking is a complete mystery to me.

Yes, it is TransType from FontLab. 
Quickest way to get a visual assessment.
And you can fix the style groups and other names (e.g. Typographic), and weights, etc.
Here is the full interface (while fixing the Display fonts):
![TransType Inter 4 Beta 3 Desktop Display fixed](https://user-images.githubusercontent.com/844920/194146283-cc5cfb9e-2e77-45d3-aeee-a28dab185751.png)

@aemi-dev I fixed the names and weights for 4 Beta 3.
Please test these fonts to see if this fixes your issue.
[Inter.4.Beta.3.Desktop.fixed.zip](https://github.com/rsms/inter/files/9718460/Inter.4.Beta.3.Desktop.fixed.zip)

**Comment by aemi-dev** [comment] 2022-10-05 19:46
<img width="1428" alt="Screenshot 2022-10-05 at 21 44 18" src="https://user-images.githubusercontent.com/42325924/194148766-3e03f92c-dc1f-4fb5-b39b-007f5e8b6b83.png">

@kenmcd @rsms This is almost good. Now, it's Display Regular which is used as the default variant of Inter. @rsms Why didn't you keep Inter Display as a distinct font? It makes it far easier to use and it would prevent this sort of weird behaviors. It's only my opinion but Inter being my go-to font for almost everything, this little change will cause me a lot of trouble.

**Comment by kenmcd** [comment] 2022-10-05 19:49
> @kenmcd @rsms This is almost good. Now, it's Display Regular which is used as the default variant of Inter. @rsms Why didn't you keep Inter Display as a distinct font? It makes it far easier to use and it would prevent this sort of weird behaviors. It's only my opinion but Inter being my go-to font for almost everything, this little change will cause me a lot of trouble.

Yeah, I was concerned about that.
Let me make you a Display set as a separate Typographic family.
Be back in a few minutes.

**Comment by aemi-dev** [comment] 2022-10-05 19:59
Nah @kenmcd you don't have to do that. It won't fix the fact Rasmus changed it. I mean, it's a problem for me, I don't know if it is for other people but at least he heard us on the different problems here.

**Comment by rsms** [comment] 2022-10-05 20:40
I added a workaround for the fontmake bug in c79709096b7386060be4be7766537bea6d464c4a. Here's a build: 
[Inter-4.00-c79709096b.zip](https://github.com/rsms/inter/files/9718814/Inter-4.00-c79709096b.zip)

> @aemi-dev Why didn't you keep Inter Display as a distinct font? It makes it far easier to use and it would prevent this sort of weird behaviors. It's only my opinion but Inter being my go-to font for almost everything, this little change will cause me a lot of trouble.

It's primarily a variable font where "Display" is an opsz axis. Tooling makes it easy to produce static fonts with "Display" style but doesn't make it easy to produce static fonts where all "Display" styles becomes a separate family. Patches & suggestions welcome! Would probably be more ergonomic to have a separate family called "Inter Display".

However, when the variable font is installed, all instances, including the Display styles, will be listed in most apps as separate styles. Here's what it looks like in Figma:

<img width="96" alt="Screen Shot 2022-10-05 at 13 39 11" src="https://user-images.githubusercontent.com/47046/194159019-a7f566e7-1429-4e74-8636-8d36b094ef04.png">

Thank you both for helping out with this!

**Comment by aemi-dev** [comment] 2022-10-05 20:54
@kenmcd Obviously it worked. Thanks

@rsms It's a beta so I understand it is something I would have to wait for but it's definitely worth the work in term of usability (Apple iWorks suite does not offer the same UI as does Figma for example, nor Word and a lot of other).

@rsms One who doesn't ask, doesn't get anything. You can still ask them. It would be a great gift/compensation for the work you've done on Inter, now used wiiiiidely. Can't get enough of the fact I discovered the version 2 of Inter years ago and now I see it everywhere.

**Comment by kenmcd** [comment] 2022-10-05 23:30
> I added a workaround for the fontmake bug in [c797090](https://github.com/rsms/inter/commit/c79709096b7386060be4be7766537bea6d464c4a). Here's a build:
> [Inter-4.00-c79709096b.zip](https://github.com/rsms/inter/files/9718814/Inter-4.00-c79709096b.zip)

The weights are now good.
But the Display Bold and Bold Italic are still in separate style groups.
This will cause problems in LibreOffice, Word, etc. on Windows, and applications on Linux such as LibreOffice, and even on macOS such as Affinity Publisher, LibreOffice, Word, etc.

**Comment by kenmcd** [comment] 2022-10-05 23:48
> Tooling makes it easy to produce static fonts with "Display" style but doesn't make it easy to produce static fonts where all "Display" styles becomes a separate family. Patches & suggestions welcome! Would probably be more ergonomic to have a separate family called "Inter Display".

To make the Bold and Italic buttons work as expected, some applications appear to connect the typographic family to the style group family via the expected RIBBI "normal" style group. So when these do not match applications can get confused. I cannot remember if it is Glyphs App or FontLab or ?? even has a "best practices" recommendation to make these match.

I still do not fully understand how the GF, UFO/designspace, fonttools, etc. build process works. But I have seen other font families which are built separately. So I will keep an eye out on how it is done.

**Comment by kenmcd** [comment] 2022-10-05 23:52
> @kenmcd Obviously it worked. Thanks

Great. So the original mystery is solved.

**Comment by aemi-dev** [comment] 2022-10-06 05:33
> This will cause problems in LibreOffice, Word, etc. on Windows, and applications on Linux such as LibreOffice, and even on macOS such as Affinity Publisher, LibreOffice, Word, etc.

@kenmcd We're on the same page here.

**Comment by rsms** [comment] 2022-10-06 16:36
> To make the Bold and Italic buttons work as expected, some applications appear to connect the typographic family to the style group family via the expected RIBBI "normal" style group. So when these do not match applications can get confused. I cannot remember if it is Glyphs App or FontLab or ?? even has a "best practices" recommendation to make these match.

Maybe this one? The Glyphs educational content is so good.
https://glyphsapp.com/learn/naming

By renaming "Display Regular" to "Display" (and updating the linking, which I might not do properly?) we are getting closer. Display Bold Italic is not linked correctly though:

<img width="1301" alt="r9s8tnueir" src="https://user-images.githubusercontent.com/47046/194369579-265d13ea-b235-4977-9b9f-87fae8fec508.png">

<img width="1728" alt="nrast8u9ri" src="https://user-images.githubusercontent.com/47046/194369609-6c9722d9-cccb-4965-8092-959726281772.png">

**Comment by rsms** [comment] 2022-10-06 16:40
Ah! I got it!

<img width="1292" alt="Screen Shot 2022-10-06 at 09 37 31" src="https://user-images.githubusercontent.com/47046/194370195-b1d30f94-6c43-41cf-a1a2-fbd53c03365e.png">

<img width="962" alt="Screen Shot 2022-10-06 at 09 37 47" src="https://user-images.githubusercontent.com/47046/194370201-28358175-5e57-4e7e-8ca8-d7849960f1a9.png">

Had to link "Display Bold Italic" with "Display" (not "Display Bold")

**Comment by rsms** [comment] 2022-10-06 16:42
Here's a build with these changes:
[Inter-4.00-2ca005973c.zip](https://github.com/rsms/inter/files/9726852/Inter-4.00-2ca005973c.zip)

**Comment by aemi-dev** [comment] 2022-10-06 21:53
> Here's a build with these changes:
> [Inter-4.00-2ca005973c.zip](https://github.com/rsms/inter/files/9726852/Inter-4.00-2ca005973c.zip)

Yes the weight problem is fixed but now there's still the "problem" of both styles being labeled as Inter rather than Inter and Inter Display. Do you think you'll work on it for the v4 release ?

**Comment by kenmcd** [comment] 2022-10-06 21:57
> Here's a build with these changes: [Inter-4.00-2ca005973c.zip](https://github.com/rsms/inter/files/9726852/Inter-4.00-2ca005973c.zip)

I checked the 4.0-beta4 pre-release at all looks good now. 
Yabba-dabba-do!
p.s. also checked the dotmaconcomb - and is is fixed!

See you got TransType. 
Just a couple notes.
It is/was designed for non-font-geek normal people.
For them to convert various formats.
Because it is for end-users it does something "helpful" with the OS2 weights to work-around the old Windows GDI "enhancing" of the lighter weights (weight set to less than 300).
It sets the Thin to 250, the ExtraLight to 265, etc.
Which is great for some Windows user who needs it to "just work."
But that will not fly with Google Fonts for example who wants the "correct" weights for the web.
So just be aware the fonts will not be production-ready.

But TransType is GREAT for checking the style groups, for checking naming errors, for checking OS2 weight settings, for checking OS2 width settings, and for completely renaming entire font families.
When something does not work (someone posts an issue) the first thing I do is drop the fonts into TransType and take a look.
Great troubleshooting tool.

**Comment by kenmcd** [comment] 2022-10-06 22:11
> Yes the weight problem is fixed but now there's still the "problem" of both styles being labeled as Inter rather than Inter and Inter Display. Do you think you'll work on it for the v4 release ?

@rsms This issue will just get worse when you add some more instances for optical size, etc.
InDesign uses the OS/2 width and weight to sort the fonts in their font menu.
Other applications may not do this.
For example in Affinity Publisher the Merriweather family shows up as a loooooooog list of all 120 fonts - which is crazy.
Highly recommend making separate typographic families for optical size and weight.
Makes it far more manageable in many other applications.
And avoids issues like @aemi-dev is having here.

**Comment by rsms** [comment] 2022-10-07 00:25
> now there's still the "problem" of both styles being labeled as Inter rather than Inter and Inter Display. Do you think you'll work on it for the v4 release ?

I will try. I don't think fontmake makes this easy. Think I'll have to write a post processing script that edits metadata (and style linking) to get it done, which will have low prio for release 4.0 (there is TONS of other work to be done, all in my spare time.) Any ideas or contributions for making static-fonts only split into separate family names are welcome!

**Comment by jenskutilek** [comment] 2022-10-07 11:16
In Glyphs, you would set the instances to not WWS-compatible, and supply WWS-compatible names like shown in the screenshot.

![Bildschirmfoto 2022-10-07 um 13 13 40](https://user-images.githubusercontent.com/3185950/194540582-66f4e501-d8ef-4bbc-9e5c-125052b1f3f4.png)

That would present the fonts as separate families for apps that don't support mixing the normal with display styles.

But this doesn't seem to be supported by fontmake, it doesn't write the WWS family and style names to name IDs 21 and 22.

**Comment by anthrotype** [comment] 2022-10-07 11:21
> But this doesn't seem to be supported by fontmake, it doesn't write the WWS family and style names to name IDs 21 and 22.

that's strange. I can see ufo2ft supports writing those if the UFO openTypeNameWWSFamilyName and openTypeNameWWSSubfamilyName font.info parameters:

https://github.com/googlefonts/ufo2ft/blob/9afae22ef9265cea350d66fecf1525c6ce54ff27/Lib/ufo2ft/outlineCompiler.py#L429-L430

And I can see that glyphsLib seems to be exporting those (search "WWS" in this file https://github.com/googlefonts/glyphsLib/blob/main/Lib/glyphsLib/builder/custom_params.py). Please file an issue in either glyphsLib or ufo2ft or fontmake if in doubt, with a repro

**Comment by rsms** [comment] 2022-10-07 23:31
@jenskutilek I tried it (setting WWS names for all display instances) and indeed the OTFs produced by fontmake does not contain that information.

**Comment by rsms** [comment] 2022-10-07 23:37
Thank you @jenskutilek for filing this issue: https://github.com/googlefonts/glyphsLib/issues/820

**Comment by rsms** [comment] 2022-10-08 00:46
I've added WWS entries for the Display styles of the static fonts. @aemi-dev can you try this new build and see if it works as expected? (I'm not sure how to test this myself beyond inspecting the font files and making sure they have seemingly-correct WWS entries)

[Inter-4.00-7cc0ab62e6.zip](https://github.com/rsms/inter/files/9738030/Inter-4.00-7cc0ab62e6.zip)

**Comment by aemi-dev** [comment] 2022-10-08 01:18
This build defaults to Display Regular.

<img width="677" alt="Screenshot 2022-10-08 at 03 17 45" src="https://user-images.githubusercontent.com/42325924/194680421-2b4be333-4a22-4f07-ab40-a50edc7d7ac6.png">

<img width="134" alt="Screenshot 2022-10-08 at 03 18 18" src="https://user-images.githubusercontent.com/42325924/194680436-159c0947-d080-4033-8c27-06eb5d09d7e7.png">

**Comment by rsms** [comment] 2022-10-14 23:28
Any ideas how to make it default to "Regular" instead?

**Comment by aemi-dev** [comment] 2022-10-15 00:18
I don't have any technical knowledge here but is it because for the same weight, style names are sorted alphabetically?

**Comment by kenmcd** [comment] 2022-10-15 01:53
@aemi-dev  Do you have the variable fonts installed at the same time? You should not do that as the variable instance names can conflict with the static font names. The "V" variable fonts are named that way so they do not (should not) conflict.

There are also issues with the variable instance names and master names. Tried to rename and test yesterday but FL8 did not play well with that glyphs package. I would almost get it all done and one of the masters would disappear. Was making me crazy(ier). Perhaps will try again tomorrow with FL7.

**Comment by aemi-dev** [comment] 2022-10-15 09:28
Nah, I don't have the Variable font installed right now. And yea the V suffix should avoid this sort of problems. At least now I have a Display Regular as a default and it does not bother me that much. But yeah, that's still not it.

**Comment by aravinddesign** [comment] 2022-10-15 16:39
> <img alt="Screen Shot 2022-10-05 at 13 39 11" width="96" src="https://user-images.githubusercontent.com/47046/194159019-a7f566e7-1429-4e74-8636-8d36b094ef04.png">

@rsms I have installed the Inter v4 beta. But I cannot see the display fonts on Figma like how you get.

Here's what I did:
1. I have removed the existing Inter v3 
2. Installed Inter v4 [Inter-4.00-7cc0ab62e6.zip](https://github.com/rsms/inter/files/9738030/Inter-4.00-7cc0ab62e6.zip)
3. Disabled Google fonts in Figma
4. Restarted Figma, but it didn't work 

I could see the Display fonts available in Pages and other apps. But not on Figma.

**Comment by rsms** [comment] 2022-10-15 19:11
@aravinddesign I have the "Inter V" fonts installed. Specifically:
- `~/Library/Fonts/InterV.var.ttf`
- `~/Library/Fonts/InterV-Italic.var.ttf`

**Comment by aravinddesign** [comment] 2022-10-15 19:31
@rsms I've installed **Inter V** font and it works. Thank you!

**Comment by rsms** [comment] 2022-10-16 17:48
[v4.0-beta6](https://github.com/rsms/inter/releases/tag/v4.0-beta6) includes the changes we've made so far

**Comment by rsms** [comment] 2023-04-21 21:33
I ... think we can close this issue?

**Closed by rsms** 2023-04-21 21:33 UTC
Labels: bug, v4
