### ISSUE TITLE
Funky asterisks

### ISSUE THREAD

**Issue by congp** [rsms/inter#67] opened 2018-08-30 17:31 UTC
Whenever you have more than one asterisk side-by-side, it looks like this (notice the third asterisk)

<img width="393" alt="screenshot 2018-08-30 11 29 37" src="https://user-images.githubusercontent.com/11388209/44868506-37e24a80-ac48-11e8-9cda-44be6cae91d6.png">

Maybe some weird OpenType feature (shrug).

**Comment by rsms** [comment] 2018-08-30 18:15
Duplicate of #57

**Closed by rsms** 2018-08-30 18:15 UTC
