### ISSUE TITLE
iOS dev: 30px and above font sizes rendering with lowest font weight

### ISSUE THREAD

**Issue by startrick** [rsms/inter#589] opened 2023-06-22 05:40 UTC
**Describe the bug**
I am using Inter 4.0-beta9g in my project. Text with font sizes at 30px and above are rendering as a thin font, and disregarding the font weight assigned to it. I have observed this in both Safari and Chrome in my iPhone 13 Pro.

**Screenshots**
![IMG_6342](https://github.com/rsms/inter/assets/25145429/01ad6dcb-23b2-4919-9fe3-abfe1a575df2)

**Environment**
- iPhone 13 Pro
- Safari and Chrome
- Inter 4.0-beta9g

**Comment by startrick** [comment] 2023-06-22 05:55
I figured that explicitly adding opsz value in the style makes it work, but is that expected?
style={{
        fontVariationSettings: "'opsz' 28",
      }}

**Comment by kenmcd** [comment] 2023-06-23 01:01
Some browsers, on some operating systems, have problems handling the `opsz` axis properly.
There have been a number of issues posted regarding the Google Fonts web pages where things did not work as expected.
The work-around was to explicitly set the `opsz` (like you did).
Please test your iOS browsers on the Google Fonts variable fonts which have an `opsz` axis (on their Type-Tester pages).
Here: https://fonts.google.com/variablefonts?vfaxis=opsz#font-families 
(if the font list is not showing, re-select `opsz` in the search box select list)

Have you tested some other fonts?
You do not mention how you are constructing your project.
Some of the Apple API font tools do affect the handling of optical size.
Please test some other fonts.
Segoe UI Variable and Nunito Sans Variable may be good choices.

**Segoe UI Variable - Microsoft**
Optical Size (opsz)
Default: 10.5
Range: 5-36
_Design toolkits and samples for Windows apps - Fonts_
https://learn.microsoft.com/en-us/windows/apps/design/downloads/#fonts
Download (direct link): https://aka.ms/SegoeUIVariable

**Nunito Sans Variable**
https://fonts.google.com/specimen/Nunito+Sans
Optical Size (opsz)
Default: 12
Range: 6-12

Both of those have more limited `opsz` ranges than the Apple System Font - which may be what the API expects (the way you have coded it).

Your example text above is the default `opsz` of 28, and the not-default weight of 100 - which is quite odd.

Please test the browsers and the fonts and then we can go from there.
Could be an issue with Inter 4.0-beta9g, but your odd results may indicate something else.

**Comment by rsms** [comment] 2023-09-12 00:40
@startrick did kenmcd's ideas help? Can we close this or do you still think there's an issue with Inter that we should look into?

**Comment by startrick** [comment] 2023-09-13 09:27
@rsms Yes and Thanks @kenmcd. BTW I found a couple of more websites on Inter4 which when rendered on my iPhone shows the thin font styles. I am manually adding opsz values to my larger font sizes and that seems to have worked for me.
The new website looks sleek with Inter4. Thanks a ton!

**Comment by rsms** [comment] 2023-11-27 20:53
Reopening this but I won't be fixing it since I have no idea where to even start.
**Open to contributions for fixes!**

**Comment by nico3333fr** [comment] 2024-01-29 16:33
Hey there, 

I'm one of Proton Mail devs => we are using Inter Sans on Proton Mail web apps (V4), and we confirm the issue on Safari iOS < v16.4.

<img width="413" alt="image" src="https://github.com/rsms/inter/assets/2578321/bc4a524b-d89a-477b-b798-c0dc934bb41e">

We are investigating too.

**Comment by kenmcd** [comment] 2024-01-29 23:17
Obviously a browser issue given that it is fixed in v16.4-16.6.
So the only way to know if the issue in the <16.4 is caused by something in Inter is to see some other fonts _which do work_ in the older version.
Please test with these three other interface fonts which also have an optical size axis:

**Segoe UI Variable** - download link above

**Roboto Flex** - https://github.com/googlefonts/roboto-flex/releases

**System Font** (SFNS.ttf) - comes with macOS

Do any or all of these work as expected in <16.4?
What font sizes are you using?
(could be related to min/max/default settings)

What happens with the iOS browsers on this test page?
SNAFU: Optical Sizes Browser Check
https://graphicore.github.io/varla-varfo/explorations/techniques/opsz-browser-check.html

**Comment by rsms** [comment] 2024-03-23 16:15
Sounds like Apple fixed their bug

https://github.com/rsms/inter/issues/649#issuecomment-1826460465

Can you please confirm @startrick ?

**Closed** 2024-03-24 19:27 UTC
Labels: help wanted, Needs Info, opsz, technical

**Comment by brc-dd** [comment] 2024-04-18 17:33
Just for visibility, this is the upstream issue link - https://github.com/WebKit/WebKit/pull/10126

**Comment by yerlantemir** [comment] 2024-08-11 08:03
The solution in this blogpost fixed the issue for me https://clagnut.com/blog/2423
