### ISSUE TITLE
PowerPoint on macOS renders Inter with wrong letter spacing

### ISSUE THREAD

**Issue by SebastianAigner** [rsms/inter#603] opened 2023-07-27 21:48 UTC
**Describe the bug**
Inter looks oddly spaced when rendered in PowerPoint.
(Initially brought up at https://twitter.com/sebi_io/status/1684551882386165760)

**To Reproduce**
1. Install Inter (Version 4.000;git-4146feb) on macOS via the `ttc` or individual `ttf` files.
2. Open PowerPoint and type a word like "Tabular"
3. Observe that the spacing between "T" and "a" is way off.

**Expected behavior**
The font should look more like when rendered through other text shapers.

**Screenshots**
![image](https://github.com/rsms/inter/assets/2178959/7db53f2c-7396-4682-8bad-25502855d77b)

**Environment**
- OS: macOS 13.2.1 (22D68)
- App that renders the font: PowerPoint 16.75
- Version of font: Version 4.000;git-4146feb (but also reproduced with 3.x)

**Comment by RandomMaerks** [comment] 2023-08-16 15:31
The massive spacing (or kerning) is not a bug within the font itself. It's mostly Powerpoint's fault.

Powerpoint is known for kerning errors when it comes to custom fonts because the program doesn't support kerning class table or something like that (apologies for the probably wrong term. im literally a type designer bruh)

Word has a "compatibility mode" where you can access OpenType features and kerning, but Powerpoint for some reason doesn't seem to have this option. Even though these are both Microsoft products.

It might not be true, but the bug and the frustration of many designers who use Powerpoint for design purposes are definitely real.

**Comment by kenmcd** [comment] 2023-08-16 22:35
I assume you have the PowerPoint setting `Kerning for fonts:` enabled - because the Arial is kerned, and the first line of Inter is kerned. And the default is `for text 12pt and above` so it should affect your 18pt type.
The line you cut and pasted has no kerning.
So you may want to check the above settings for that particular text.

The kerning issues are with PowerPoint.
The kerning in Inter is fine, and it works properly in applications which work properly.

**Comment by rsms** [comment] 2023-08-29 16:46
First off, thank you for the thorough report! I really appreciate it.

What's going on is that kerning data is not being used. A shorter, more obvious example is "LTo" which should have significantly less space when the font's kerning data is used.

Now, I can also reproduce this, including Microsoft Word. But I can't reproduce it in any other software, which leads me to assume this is a bug in the Microsoft products triggered by something in Inter.

Microsoft Word: (fails to apply kerning)

<img width="845" alt="Screen Shot 2023-08-29 at 09 32 33" src="https://github.com/rsms/inter/assets/47046/cdd2d7be-2d28-4e84-b83d-01100cd52d42">

Apple TextEdit: (correctly uses kerning; same for every other software I've tried)

<img width="585" alt="Screen Shot 2023-08-29 at 09 33 41" src="https://github.com/rsms/inter/assets/47046/94c270c7-d524-45c4-b730-d3af889dcc05">

It gets interesting when I copy-paste from Word to TextEdit — kerning is disabled! And TextEdit's (technically macOS's) typography panel does not show kerning as being disabled:

<img width="766" alt="Screen Shot 2023-08-29 at 09 39 21" src="https://github.com/rsms/inter/assets/47046/2a031a91-e7ac-40e0-bca8-e7ad9f49360f">

But when I inspect the Rich Text Format output of what Word produces I noticed something weird: (A = correct, B = pasted from Word)

<img width="1645" alt="Screen Shot 2023-08-29 at 09 44 08" src="https://github.com/rsms/inter/assets/47046/7d64e885-cb8c-470d-b2e6-cf415d884d12">

Notice the highlighted text: Word is **_explicitly disabling kerning_**

```rtf
\expnd0\expndtw0\kerning0
```

([Complete RTF output from Word here](https://gist.github.com/rsms/45336e7f0d1beb76fa8c3980fc05d6d9))

**Comment by rsms** [comment] 2023-08-29 16:53
Workaround: Enable kerning via the "Font" panel:

1.

<img width="766" alt="Screen Shot 2023-08-29 at 09 51 30" src="https://github.com/rsms/inter/assets/47046/0c368e05-8c17-4f0e-b169-bb306456569d">

2. in the "advanced" tab, enable kerning (enter a small number; it defaults to `72` for some crazy reason)

<img width="702" alt="Screen Shot 2023-08-29 at 09 50 07" src="https://github.com/rsms/inter/assets/47046/ea60d58a-7059-4493-af10-bba5ca7dbbab">

Result:

<img width="866" alt="Screen Shot 2023-08-29 at 09 50 12" src="https://github.com/rsms/inter/assets/47046/1f15ec59-7fec-4e94-afac-8876e9824d29">

**Comment by rsms** [comment] 2023-08-29 17:07
I'm going to close this since it doesn't seem to be anything we can do about it.

FWIW, Word disables kerning for all fonts, not just Inter. Here's a new document using Word's default font "Calibri" (an official Microsoft font bundled with Word) and indeed kerning is disabled:

<img width="941" alt="Screen Shot 2023-08-29 at 09 56 13" src="https://github.com/rsms/inter/assets/47046/1481116e-afa2-4751-8552-f5bd88f478da">

Seems like we just found a way to improve every word doc ever written: enable kerning :–P

**Closed by rsms** 2023-08-29 17:07 UTC
Labels: Microsoft/Windows
