### ISSUE TITLE
Merge Display & Text into one big VF

### ISSUE THREAD

**Issue by thierryc** [rsms/inter#447] opened 2022-03-21 19:09 UTC
Just a suggestion
Add the Display Font into the Inter variable Font like Apple does with the SF Pro.

Regular < 17 
Display > 17

<img width="455" alt="image" src="https://user-images.githubusercontent.com/197471/159345262-c18cb586-10d7-4da3-8fd5-663a19380381.png">

**Comment by ThomasRettig** [comment] 2022-03-22 02:26
Inter Display is still in development so it may be a bit premature to merge it into the existing Inter variable font. The interpolation might be an issue, too: https://github.com/rsms/inter/issues/411#issuecomment-1015797411

**Comment by thierryc** [comment] 2022-03-22 09:29
Yes, it is premature to merge it into the distribution package, but to draw it, **to have all variations in the same file has some benefits**. 
To add it later can be more work than to add it in a relatively early stage, especially for spacing.

It still just a suggestion.

**Comment by rsms** [comment] 2022-05-20 17:41
I think this would be incredibly hard to do since VFs need to have perfectly matching paths for every key-glyph of a logical-glyph. That includes number of paths, order of those paths, winding order of each path, number of control points and their order — this would mean that the [text] and Display version would have to match every glyph's design, which they currently do not (for example, regular Inter uses more bridges/traps to help in small-size legibility while Display has different goals.)

So, doable but very costly.

**Comment by rsms** [comment] 2022-05-31 20:01
Duplicate of #411 (see also: #463)

**Closed by rsms** 2022-05-31 20:01 UTC
Labels: VF, Icebox, technical
