### ISSUE TITLE
Base stand for tabular ONE

### ISSUE THREAD

**Issue by nitin2953** [rsms/inter#434] opened 2022-02-10 08:58 UTC
Base stand for ONE(1) as an alternate or default

![inter-tabular-one](https://user-images.githubusercontent.com/34852979/153370808-40bb50af-54da-4148-b4c4-ca59eae69c14.png)

**Comment by ThomasRettig** [comment] 2022-02-10 09:45
(Irrelevant side note... Do you work for Google? Google Sans is a proprietary font only given out to Google employees, so it is illegal to use it if you're not.)

**Comment by nitin2953** [comment] 2022-02-11 06:11
I had worked for google at some point but not now and I'm only using it on my private project

> (Irrelevant side note... Do you work for Google? Google Sans is a proprietary font only given out to Google employees, so it is illegal to use it if you're not one of their employees.)

**Comment by ThomasRettig** [comment] 2022-02-11 07:25
> I had worked for google at some point but not now and I'm only using it on my private project

I see, just curious!

Regarding tabular numbers, I don't have objections to it, it seems quite reasonable. I think some Inter users will benefit from that. However, I wonder if it _necessary_, since the default `1` is already pretty legible and disambiguated. That's all I can say though. I wonder, @nitin2953, is there any motivation behind your suggestion? Is it about legibility or simply for the design?  :-)

**Comment by orlp** [comment] 2022-03-20 21:49
I think the general complaint here is that the (tabular) numbers in Inter are too wide. Comparing it against my system font on the right:

![image](https://user-images.githubusercontent.com/202547/159186997-038b27e4-6743-467f-8dd7-5a3b4e8d3bf9.png)

Here's my non-typographer opinion of what the issue is:

 - The three has a tad too much space on the left in both variants.
 - The four has a bit too much space on the right in both variants.
 - The `tnum` variant erroneously adds even more space on top of the widest glyph (4).
 - The `tnum` variant of the one is aligned too much towards the left:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/202547/159187260-de6076d4-16e7-4110-9478-76c4c5d0a403.png">

I think these factors contribute to making the numbers in the `tnum` variant of Inter feel too spacious, and resolving these is a good idea before evaluating a base stand for the one.

**Comment by ThomasRettig** [comment] 2022-03-21 01:52
Agree with @orlp. In addition the Inter `4` seems a bit to optically heavy in contrast to the other numerals.

**Comment by tylermcgowan** [comment] 2022-03-31 18:48
Bumping this as well, and echo what @nitin2953 has mentioned. Depending on the combo string of numbers, the tabular `1` without the bottom crossbar can make the spacing look/feel off, especially if you had repeating 1's sandwiched between other numerals.

**Comment by i-am-the-slime** [comment] 2022-04-01 19:25
Is there any way I can get the 1 to be centred on its stem?
<img width="44" alt="image" src="https://user-images.githubusercontent.com/1588055/161328631-2ffa0a60-7751-428f-8de1-9b48f9022106.png">
To avoid the above?

**Comment by rsms** [comment] 2022-05-20 17:21
Thank you @orlp for a good take. Adding a slab to the bottom of the tabular one would stray a bit too far from the personality of Inter. Say you wanted to show tabular numbers nearby non-tabular numbers, then you'd end up with different-looking "one"s. Slab serifs is a good fit for monospace fonts and [maybe one day there will be an Inter Mono](https://github.com/rsms/inter/issues/128).

**Closed by rsms** 2022-05-20 17:21 UTC

**Comment by thenanyu** [comment] 2024-12-16 15:20
@rsms did you change your mind on this?
> Adding a slab to the bottom of the tabular one would stray a bit too far from the personality of Inter. Say you wanted to show tabular numbers nearby non-tabular numbers, then you'd end up with different-looking "one"s

We are dealing with this exact issue right now, where we have tabular and non-tabular 1s next to each other and they are different styles.

![Screenshot 2024-12-16 at 10 18 59@2x](https://github.com/user-attachments/assets/b18daa2d-1f4c-48c6-ae1e-842d0b6887bd)

**Comment by TaigaYamada** [comment] 2024-12-20 22:22
Tabular one without the bottom slab has already been implemented, and is planned to be released as part of v4.2: #579
