### ISSUE TITLE
' đ ' character of Inter UI

### ISSUE THREAD

**Issue by tue0506** [rsms/inter#100] opened 2018-12-19 13:10 UTC
Hello! I just have set your font as system font in MIUI 10. And now I'm in love with this font :)
I'm Vietnamese and Inter UI supports all of Vietnamese characters. But there are some issue with the latest version of Inter UI.
1. The 'đ' glyph has a square hole (see images I attached)

![screenshot_2018-12-19-16-36-52-306_com darkorbitstudio fontviewer](https://user-images.githubusercontent.com/31882623/50222786-e3680400-03cb-11e9-8d2d-941ed9360191.png)
![screenshot_2018-12-19-19-59-55-546_com darkorbitstudio fontviewer](https://user-images.githubusercontent.com/31882623/50222787-e3680400-03cb-11e9-9363-89f0dad7e34d.png)

2. All glyphs of Inter UI aren't alined with status bar icons. If you can, please decrease the bottom padding of all glyphs :)

![screenshot_2018-12-19-20-00-46-658_com android settings](https://user-images.githubusercontent.com/31882623/50222793-eb27a880-03cb-11e9-8626-88f43e1c28c8.png)

Thank you for this great font :)

* Sorry for my bad English :)

**Comment by rsms** [comment] 2018-12-26 01:39
1. This seems strange. Can you please provide exact version of applications and OS used to reproduce this? I can't repro this myself in Chrome, Safari nor Adobe Illustrator. It's possible this is an issue with the font renderer you're using (there are a lot of buggy renderers out there.) Also, please provide detailed information on what specific font files you're using.

2. That is definitely an issue with the layout engine and/or font renderer you're using. A significant amount of effort was put into ensuring capital letters (and numerals) of Inter UI align perfectly in the center when rendered by correctly-behaving type setters. Many were used for benchmarking. It's also possible your icons are not centered and/or that you're using a layout method (of whatever makes that graphic) that doesn't produce the desired results (for instance, in HTML the only reliable way to align images and text is to use flexbox with correct line height constants and flex properties.)

Since I can't reproduce, I'll close this for now.
Happy to open it again if we have more information and a repro case.

**Closed by rsms** 2018-12-26 01:39 UTC

**Comment by tue0506** [comment] 2018-12-26 13:40
Thanks for your reply!

1. I'm using Inter UI for my 'font' Magisk Module. I'm using the module on
MIUI 10.3 v8.12.20 Beta by Xiaomi.eu (based on Android 8.1) - Xiaomi Redmi
Note 5. Steps to reproduce the issue:
- Install Magisk v18.0 (
https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445
)
- Open Magisk Manager and install 'Inter-UI-v3.1.zip' (see the attachments)
- Reboot your device, then try to type 'đ' and see the issue
* If you don't want to root your device, simply install any 'font viewer'
apps on Play Store, then open the font file and type 'đ'

2. Your font look very similar with San Francisco font or Roboto font, but
these fonts have aligned with status bar icons perfectly. If you can,
please look into this :)

** The issue with 'đ' only happens with TTF variant of your font, the OTF
variant works very well without any issue except align of status bar icons

Finally, thanks for your great font!


Vào 8:39, Th 4, 26 thg 12, 2018 Rasmus <notifications@github.com đã viết:
