### ISSUE TITLE
4.0-beta9g - 4+ consecutive characters in contextual alternatives

### ISSUE THREAD

**Issue by aetinx** [rsms/inter#594] opened 2023-07-01 18:19 UTC
**Describe the bug**
4+ consecutive punctuation characters between CAPITAL and lowercase letters are wonky.

Red = fail, green = technically passing

![image](https://github.com/rsms/inter/assets/65425469/8b85ea0a-8568-4d8b-bdaa-46034a37e1df)

**Expected behavior**
These 3 red dots should be aligned with the first dot.

<img width="276" alt="image" src="https://github.com/rsms/inter/assets/65425469/47276c06-0696-443c-b7db-dd3985b2eadb">

**Environment**
Windows 11 22H2 22624.1391
Figma Desktop App 116.10.8
Release 4.0-beta9g

**Comment by rsms** [comment] 2023-07-13 13:43
Duplicate of #442

**Closed by rsms** 2023-07-13 13:43 UTC
