### ISSUE TITLE
SmallCaps only partially present in 4.0-beta8

### ISSUE THREAD

**Issue by TKrepo** [rsms/inter#556] opened 2023-04-12 13:01 UTC
Small Caps are nice feature to emphasize Text.

There are some Small Caps present in Inter 4.0-beta8, but only a few. Interestingly their availability depends on whether Capital or Lower Case letters are displayed as Small Caps. Some of the Stylistic Alternatives are present (Capital I), some are missing (Capital G).

Tested with the hinted TTF (Light) in LibreOffice 7.4.6 on Windows 10.

![Capture-or8](https://user-images.githubusercontent.com/73970205/231465073-630d2df6-9d2b-443a-9efd-2e18454c19ca.png)

**Comment by rsms** [comment] 2023-04-12 14:22
This is intentional (of course.) The small-cap glyphs that are present are required or needed for different reasons (other than serving a smcp feature. There’s a feature request here already for adding true small caps to Inter: #32 (won’t do this until after v4.0 is released.)

**Comment by rsms** [comment] 2023-04-12 14:24
Closing this as it’s not a bug and is already covered by #32 as a feature request

**Closed by rsms** 2023-04-12 14:24 UTC

**Comment by tim-janik** [comment] 2023-06-20 00:06
> Closing this as it’s not a bug and is already covered by #32 as a feature request

Oh, I just came here to report a regression... So v3.10 is not actually supposed to support small-caps?
For the record, typesetting "Devices" in small-caps worked in 3.10 but not the newest v4 beta.

![inter4smallcaps](https://github.com/rsms/inter/assets/281887/4a829a69-7526-429a-9770-c782aa21e718)

**Comment by rsms** [comment] 2023-06-20 01:00
> > Closing this as it’s not a bug and is already covered by #32 as a feature request
> 
> Oh, I just came here to report a regression... So v3.10 is not actually supposed to support small-caps? For the record, typesetting "Devices" in small-caps worked in 3.10 but not the newest v4 beta.
> 
> ![inter4smallcaps](https://user-images.githubusercontent.com/281887/246954672-4a829a69-7526-429a-9770-c782aa21e718.png)

The second line is faux small-caps, generated by the software you’re using, from the regular caps. That’s why the stroke weight is too thin.

**Comment by tim-janik** [comment] 2023-06-20 02:00
> The second line is faux small-caps, generated by the software you’re using, from the regular caps. That’s why the stroke weight is too thin.

Ok ,thanks for pointing that out. This is rendered with Chrome-114 on Linux btw.
Which leaves the question why 3.10 is rendered with faux small-caps when 4.0 isn't.
Just a guess, did 3.10 maybe not contain a c2sc setting?
If so, wouldn't it make sense to leave that out of the 4.0 builds until proper support is ready?
