### ISSUE TITLE
Error when exporting OTF using Glyphs App

### ISSUE THREAD

**Issue by m-f-u** [rsms/inter#281] opened 2020-05-14 14:52 UTC
**Describe the bug**
Error message:
»Glyph "circumflexacutecomb.cn" not in font.« in Class All in Row: 1

When excluded from export, next error when exporting:
»Glyph "tophalfwhitesquare" not in font.« in Class All in Row: 1

When _including_ to export, next error when exporting:
»Glyph "circumflexacutecomb.cn" not in font.« in Class All in Row: 1

...

After going through various include / exclude changes, I manage to get the font exported. Is this the expected behavior? I'm planning to export some changes and use that font for production (print and web), worrying these adjustments lead to corrupted files.

**To Reproduce**
Export to OTF using Glyphs

**Environment**
– Glyphs 2.6.4
– OS: macOS 10.15.4
– Inter 3.13

**Comment by rsms** [comment] 2020-05-23 03:01
Hm, I am unable to reproduce with Glyphs 2.6.5 (1330).
Could you try updating Glyphs?

Also, to build from source, see this guide: https://github.com/rsms/inter/blob/master/CONTRIBUTING.md
Building from Glyphs is not something that is supported. For production-quality fonts you need to use init.sh and make as described in this guide.

BTW, when I export (successfully) from Glyph, these are the settings I use:
<img width="436" alt="Screen Shot 2020-05-22 at 19 58 57" src="https://user-images.githubusercontent.com/47046/82720285-f6d56980-9c66-11ea-81fd-be7aa490df2a.png">

**Comment by m-f-u** [comment] 2020-05-24 17:31
Hi, I tried updating to the latest cutting edge version (1335 / larger than 1330) and followed your settings. I get the same result: 

»Glyph "circumflexacutecomb.cn" not in font.« in der Klasse All in Zeile: 1

init.sh works for me now. Wanted to report the bug nonetheless.

**Comment by rsms** [comment] 2020-08-17 23:43
Thank you! I'm going to close this issue since I don't know how to debug it. It's possible there's something really complex going on. I believe Glyphs uses a number of 3rd party tools "behind the scenes" that generates the font files. Things like a file system with unexpected case sensitivity or system libraries could be the issue. I suggest that you file an issue/report with Glyphs, if this prevails.

**Closed by rsms** 2020-08-17 23:43 UTC
