### ISSUE TITLE
Double storey g character variant

### ISSUE THREAD

**Issue by rben01** [rsms/inter#726] opened 2024-07-29 16:54 UTC
I prefer double storey ‘g’ to single storey. It would be great if a character variant were added for it.

**Comment by inferno986return** [comment] 2024-09-12 17:03
While certainly less common in neo-grotesques, it can certainly work as Akkurat demonstrates nicely: https://lineto.com/typefaces/akkurat#family

**Comment by rsms** [comment] 2024-11-15 21:56
Duplicate of #539

Also, please do not ignore [the issue template](https://github.com/rsms/inter/issues/new?assignees=&labels=&projects=&template=feature_request.md)

**Closed by rsms** 2024-11-15 21:56 UTC
